---
title: "3ERA PRESENTACIÓN"
author: "CONSUELO - XARIS"
date: "2024-10-05"
output: html_document
---
```{r}
library(rio)
data_escaños=import("(escaños ocupados)P_Data_Extract_From_Gender_Statistics.xlsx")
data_PBI=import("(Crecimiento del PBI)P_Data_Extract_From_Gender_Statistics (1).xlsx")
data_edusuperior=import("(educación superior)P_Data_Extract_From_Gender_Statistics (2).xlsx")
data_corrupcion=import("(control de corrupción)P_Data_Extract_From_World_Development_Indicators (3).xlsx")
data_estabilidadausencia=import("(estabilidad política y ausencia)P_Data_Extract_From_World_Development_Indicators (4).xlsx")
data_fuerzalaboralfemenina=import("(fuerza laboral)P_Data_Extract_From_Gender_Statistics (3).xlsx")
```

**DATA DE ESCAÑOS**

```{r}

#eliminar las últimas filas
data_escaños_ok=data_escaños_ok[-c(218:222),]
```

**DATA DE EDUCACIÓN SUPERIOR**

```{r}
#eliminar filas 
data_edusuperior_ok=data_edusuperior[-c(218:222),]
```
**DATA DE ESTABILIDAD POLÍTICA Y AUSENCIA DE VIOLENCIA**

```{r}
#eliminar filas 
data_estabilidadausencia_ok=data_estabilidadausencia[-c(218:222),]
```
**DATA DE PBI**

```{r}
#eliminar filas 
data_PBI_ok=data_PBI[-c(218:222),]
```
**DATA FUERZA LABORALFEMENINA**

```{r}
#eliminar filas 
data_fuerzalaboralfemenina_ok=data_fuerzalaboralfemenina[-c(218:222),]
```
**DATA CORRUPCIÓN**

```{r}
#eliminar filas 
data_corrupcion_ok=data_corrupcion[-c(218:222),]
```

```{r}
#eliminar una fila en específico "British Virgin Islands"

data_corrupcion_ok <- data_corrupcion[-28, ]
data_edusuperior_ok <- data_edusuperior[-28, ]
data_escaños_ok <- data_escaños[-28, ]
data_estabilidadausencia_ok <- data_estabilidadausencia[-28, ]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina[-28, ]
data_PBI_ok <- data_PBI[-28, ]
```

```{r}
#eliminar una fila en específico Curacao (51)

data_corrupcion_ok <- data_corrupcion[-51, ]
data_edusuperior_ok <- data_edusuperior[-51, ]
data_escaños_ok <- data_escaños[-51, ]
data_estabilidadausencia_ok <- data_estabilidadausencia[-51, ]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina[-51, ]
data_PBI_ok <- data_PBI[-51, ]
```

```{r}
#eliminar una fila en específico Faroe Islands (66)

data_corrupcion_ok <- data_corrupcion[-66, ]
data_edusuperior_ok <- data_edusuperior[-66, ]
data_escaños_ok <- data_escaños[-66, ]
data_estabilidadausencia_ok <- data_estabilidadausencia[-66, ]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina[-66, ]
data_PBI_ok <- data_PBI[-66, ]

```

```{r}
#eliminar una fila en específico Gibraltar(76)

data_corrupcion_ok <- data_corrupcion[-76, ]
data_edusuperior_ok <- data_edusuperior[-76, ]
data_escaños_ok <- data_escaños[-76, ]
data_estabilidadausencia_ok <- data_estabilidadausencia[-76, ]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina[-76, ]
data_PBI_ok <- data_PBI[-76, ]
```

```{r}
#eliminar una fila en específico Isle of Man (95), solo tiene en PBI

data_corrupcion_ok <- data_corrupcion[-95, ]
data_edusuperior_ok <- data_edusuperior[-95, ]
data_escaños_ok <- data_escaños[-95, ]
data_estabilidadausencia_ok <- data_estabilidadausencia[-95, ]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina[-95, ]
data_PBI_ok <- data_PBI[-95, ]
```

```{r}
#eliminar una fila en específico Northern Mariana Islands (147), solo tiene en PBI

data_corrupcion_ok <- data_corrupcion[-147, ]
data_edusuperior_ok <- data_edusuperior[-147, ]
data_escaños_ok <- data_escaños[-147, ]
data_estabilidadausencia_ok <- data_estabilidadausencia[-147, ]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina[-147, ]
data_PBI_ok <- data_PBI[-147, ]
```

```{r}
#eliminar una fila en específico St. Martin (French part) (184), solo tiene en PBI

data_corrupcion_ok <- data_corrupcion[-184, ]
data_edusuperior_ok <- data_edusuperior[-184, ]
data_escaños_ok <- data_escaños[-184, ]
data_estabilidadausencia_ok <- data_estabilidadausencia[-184, ]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina[-184, ]
data_PBI_ok <- data_PBI[-184, ]
```

```{r}
#eliminar una fila en específico Turks and Caicos Islands(201), solo tiene en PBI

data_corrupcion_ok <- data_corrupcion[-201, ]
data_edusuperior_ok <- data_edusuperior[-201, ]
data_escaños_ok <- data_escaños[-201, ]
data_estabilidadausencia_ok <- data_estabilidadausencia[-201, ]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina[-201, ]
data_PBI_ok <- data_PBI[-201, ]
```

**ELIMINAR COLUMNAS*

```{r}
# Eliminar la columna 2
data_PBI_ok <- data_PBI_ok[, -2]
data_corrupcion_ok <- data_corrupcion_ok[, -4]
data_edusuperior_ok <- data_edusuperior_ok[, -2]
data_escaños_ok <- data_escaños_ok[, -2]
data_estabilidadausencia_ok <- data_estabilidadausencia_ok[, -4]
data_fuerzalaboralfemenina_ok <- data_fuerzalaboralfemenina_ok[, -2]

# Verifica los cambios
head(data_PBI_ok)
```

**CAMBIAR NOMBRES DE LAS VARIABLES**

```{r}
# Reemplazar todas las filas de la columna 3 con el valor "corrupcion"
data_corrupcion_ok[, 3] <- "corrupcion"

# Verifica los primeros cambios
head(data_corrupcion_ok)
```


```{r}
# Reemplazar todas las filas de la columna 3 con el valor "educacion_superior"
data_edusuperior[, 1] <- "educacion_superior"

# Verifica los primeros cambios
head(data_edusuperior)
```
```{r}
# Reemplazar todas las filas de la columna 3 con el valor "educacion_superior"
data_escaños_ok[, 1] <- "escaños"

# Verifica los primeros cambios
head(data_escaños_ok)
```
```{r}
# Reemplazar todas las filas de la columna 3 con el valor "estabilidad_politica"
data_estabilidadausencia_ok[, 3] <- "estabilidad_politica"

# Verifica los primeros cambios
head(data_estabilidadausencia_ok)
```
```{r}
# Reemplazar todas las filas de la columna 3 con el valor "fuerza_laboral"
data_fuerzalaboralfemenina_ok[, 1] <- "fuerza_laboral"

# Verifica los primeros cambios
head(data_fuerzalaboralfemenina_ok)
```
```{r}
# Reemplazar todas las filas de la columna 3 con el valor "PBI"
data_PBI_ok[, 1] <- "PBI"

# Verifica los primeros cambios
head(data_PBI_ok)
```



