---
title: "2DA PRESENTACIÓN"
author: "CONSUELO ESCOBAR - XARIS VALLADARES"
date: "2024-10-05"
output: html_document
---
```{r}
library(rio)
data_escaños=import("(escaños ocupados)P_Data_Extract_From_Gender_Statistics.xlsx")
data_PBI=import("(Crecimiento del PBI)P_Data_Extract_From_Gender_Statistics (1).xlsx")
data_edusuperior=import("(educación superior)P_Data_Extract_From_Gender_Statistics (2).xlsx")
data_corrupcion=import("(control de corrupción)P_Data_Extract_From_World_Development_Indicators (3).xlsx")
data_estabilidadausencia=import("(estabilidad política y ausencia)P_Data_Extract_From_World_Development_Indicators (4).xlsx")
data_fuerzalaboralfemenina=import("(fuerza laboral)P_Data_Extract_From_Gender_Statistics (3).xlsx")
data_igualdad=import("(igualdad)P_Data_Extract_From_Country_Policy_and_Institutional_Assessment.xlsx")
```

**ELIMINAR ÚLTIMAS FILAS**

```{r}
data_escanos_ok <- data_escaños %>%
  slice(-c(218, 219, 220, 221, 222))
data_corrupcion_ok <- data_corrupcion %>%
  slice(-c(218, 219, 220, 221, 222))
data_educacion_superior_ok <- data_edusuperior %>%
  slice(-c(218, 219, 220, 221, 222))
data_estabilidad_politica_ok <- data_estabilidadausencia %>%
  slice(-c(218, 219, 220, 221, 222))
data_fuerza_laboral_ok <- data_fuerzalaboralfemenina %>%
  slice(-c(218, 219, 220, 221, 222))
data_PBI_ok <- data_PBI %>%
  slice(-c(218, 219, 220, 221, 222))
data_igualdad_ok <- data_igualdad %>%
  slice(-c(84, 85, 86, 87, 88))
```

**CAMBIAMOS EL NOMBRE DEL AÑO**

```{r}
data_corrupcion_ok <- data_corrupcion_ok %>%
  rename_with(~ gsub(" \\[YR.*\\]", "", .))  # Quitar la parte "[YR ...]" y el espacio antes
data_educacion_superior_ok <- data_educacion_superior_ok %>%
  rename_with(~ gsub(" \\[YR.*\\]", "", .))
data_escanos_ok <- data_escanos_ok %>%
  rename_with(~ gsub(" \\[YR.*\\]", "", .))
data_estabilidad_politica_ok <- data_estabilidad_politica_ok %>%
  rename_with(~ gsub(" \\[YR.*\\]", "", .))
data_fuerza_laboral_ok <- data_fuerza_laboral_ok %>%
  rename_with(~ gsub(" \\[YR.*\\]", "", .))
data_PBI_ok <- data_PBI_ok %>%
  rename_with(~ gsub(" \\[YR.*\\]", "", .))
data_igualdad_ok <- data_igualdad_ok %>%
  rename_with(~ gsub(" \\[YR.*\\]", "", .))
```

**JUNTAR TODO EN UNA SOLA DATA**

```{r}
library(dplyr)
library(tidyr)

# Transformar a formato largo utilizando pivot_longer
data_corrupcion_long <- data_corrupcion_ok %>%
  pivot_longer(cols = starts_with("20"), 
               names_to = "año", 
               values_to = "corrupcion")

data_educacion_superior_long <- data_educacion_superior_ok %>%
  pivot_longer(cols = starts_with("20"), 
               names_to = "año", 
               values_to = "educacion_superior")

data_escanos_long <- data_escanos_ok %>%
  pivot_longer(cols = starts_with("20"), 
               names_to = "año", 
               values_to = "escanos")

data_estabilidad_politica_long <- data_estabilidad_politica_ok %>%
  pivot_longer(cols = starts_with("20"), 
               names_to = "año", 
               values_to = "estabilidad_politica")

data_fuerza_laboral_long <- data_fuerza_laboral_ok %>%
  pivot_longer(cols = starts_with("20"), 
               names_to = "año", 
               values_to = "fuerza_laboral")

data_PBI_long <- data_PBI_ok %>%
  pivot_longer(cols = starts_with("20"), 
               names_to = "año", 
               values_to = "PBI")
data_igualdad_long <- data_igualdad_ok %>%
  pivot_longer(cols = starts_with("20"), 
               names_to = "año", 
               values_to = "igualdad")

# Unir todos los datasets utilizando full_join
data_final <- data_corrupcion_long %>%
  full_join(data_educacion_superior_long, by = c("Country Code", "Country Name", "año")) %>%
  full_join(data_escanos_long, by = c("Country Code", "Country Name", "año")) %>%
  full_join(data_estabilidad_politica_long, by = c("Country Code", "Country Name", "año")) %>%
  full_join(data_fuerza_laboral_long, by = c("Country Code", "Country Name", "año")) %>%
  full_join(data_igualdad_long, by = c("Country Code", "Country Name", "año")) %>%
  full_join(data_PBI_long, by = c("Country Code", "Country Name", "año"))

# Verificar el resultado
head(data_final)

```

```{r}
# Eliminar columnas específicas

data_final <- data_final %>%
  select(-c(3, 4, 7, 8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23))

```

**ELIMINAR FILAS INNECESARIAS**

```{r}
data_final <- data_final %>%
  slice(-c(271:280, 501:510, 651:660, 751:760, 941:950, 1461:1470, 1831:1840, 2001:2010, 2091:2100))
```
**PARA ACCEDER AL ARCHIVO EN CSV**
```{r}
# Opcional: Guardar el nuevo DataFrame en un archivo CSV
write.csv(data_final, "data_final.csv", row.names = FALSE)
```

